# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
# Testing...

name: Deploy PyPi module

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build
        run: |
          git submodule update --init --recursive
          ln -s -r git-dependencies/burp-extender-api/src/main/java/burp/ sources/burp
          ln -s -r git-dependencies/jdk/src/java.base/share/classes/java/ sources/java
          python java2py/java2py.py --sourcedir sources --package burp --outfile burp/burp.py

      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          name: burp-module
          path: burp/burp.py

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'
    - name: Download module
      uses: actions/download-artifact@v2
      with:
        name: burp-module
        path: burp/
    - name: Test Package
      run: python2 -c "from burp import *"

  publish-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Download module
        uses: actions/download-artifact@v2
        with:
          name: burp-module
          path: burp/
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository testpypi dist/*

  install-test:
    runs-on: ubuntu-latest
    needs: publish-test
    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - name: Install module
        run: |
          pip install -i https://test.pypi.org/simple/ burp # For some reason, we might need to do it twice!
          pip install -i https://test.pypi.org/simple/ burp
      - name: Test module
        run: |
          python -c "from burp import *"

  publish-prod:
    runs-on: ubuntu-latest
    needs: install-test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Download module
        uses: actions/download-artifact@v2
        with:
          name: burp-module
          path: burp/
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PROD_PYPI_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository pypi dist/*